spring.application.name=ecommerce
server.port = 8080
spring.datasource.url=jdbc:mysql://localhost:3306/Ecommerce?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=VnZ6R3hQeG5tWUZmQ3dZNUZQbW1Yb0p0V0h5Z0ZJbXM=

#spring.security.user.name=admin
#spring.security.user.password=1234